### ISSUE TITLE
Not working on FreeBSD

### ISSUE THREAD

**Issue by marcotuna** [guinslym/pyexifinfo#10]
Hello, I am trying to install this module on FreeBSD 11.1 but I can't seem to get this working.
I've tried through pip and through this source code from github.

```
root@server:~/pyexifinfo # python ./setup.py install
running install
running bdist_egg
running egg_info
writing pyexifinfo.egg-info/PKG-INFO
writing top-level names to pyexifinfo.egg-info/top_level.txt
writing dependency_links to pyexifinfo.egg-info/dependency_links.txt
reading manifest file 'pyexifinfo.egg-info/SOURCES.txt'
writing manifest file 'pyexifinfo.egg-info/SOURCES.txt'
installing library code to build/bdist.freebsd-11.1-RELEASE-amd64/egg
running install_lib
running build_py
creating build/bdist.freebsd-11.1-RELEASE-amd64/egg
creating build/bdist.freebsd-11.1-RELEASE-amd64/egg/pyexifinfo
copying build/lib/pyexifinfo/pyexifinfo.py -> build/bdist.freebsd-11.1-RELEASE-amd64/egg/pyexifinfo
copying build/lib/pyexifinfo/__init__.py -> build/bdist.freebsd-11.1-RELEASE-amd64/egg/pyexifinfo
byte-compiling build/bdist.freebsd-11.1-RELEASE-amd64/egg/pyexifinfo/pyexifinfo.py to pyexifinfo.pyc
byte-compiling build/bdist.freebsd-11.1-RELEASE-amd64/egg/pyexifinfo/__init__.py to __init__.pyc
creating build/bdist.freebsd-11.1-RELEASE-amd64/egg/EGG-INFO
copying pyexifinfo.egg-info/PKG-INFO -> build/bdist.freebsd-11.1-RELEASE-amd64/egg/EGG-INFO
copying pyexifinfo.egg-info/SOURCES.txt -> build/bdist.freebsd-11.1-RELEASE-amd64/egg/EGG-INFO
copying pyexifinfo.egg-info/dependency_links.txt -> build/bdist.freebsd-11.1-RELEASE-amd64/egg/EGG-INFO
copying pyexifinfo.egg-info/top_level.txt -> build/bdist.freebsd-11.1-RELEASE-amd64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/pyexifinfo-0.4.0-py2.7.egg' and adding 'build/bdist.freebsd-11.1-RELEASE-amd64/egg' to it
removing 'build/bdist.freebsd-11.1-RELEASE-amd64/egg' (and everything under it)
Processing pyexifinfo-0.4.0-py2.7.egg
Removing /usr/local/lib/python2.7/site-packages/pyexifinfo-0.4.0-py2.7.egg
Copying pyexifinfo-0.4.0-py2.7.egg to /usr/local/lib/python2.7/site-packages
pyexifinfo 0.4.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/site-packages/pyexifinfo-0.4.0-py2.7.egg
Processing dependencies for pyexifinfo==0.4.0
Finished processing dependencies for pyexifinfo==0.4.0
Traceback (most recent call last):
  File "./setup.py", line 95, in <module>
    result = check_if_exiftool_is_already_installed()
  File "./setup.py", line 51, in check_if_exiftool_is_already_installed
    stderr = fnull
  File "/usr/local/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by marcotuna** [comment]
I belive p5-Image-ExifTool solved this issue
`pkg install p5-Image-ExifTool`

```
root@server:~/pyexifinfo # python ./setup.py install
running install
running bdist_egg
running egg_info
writing pyexifinfo.egg-info/PKG-INFO
writing top-level names to pyexifinfo.egg-info/top_level.txt
writing dependency_links to pyexifinfo.egg-info/dependency_links.txt
reading manifest file 'pyexifinfo.egg-info/SOURCES.txt'
writing manifest file 'pyexifinfo.egg-info/SOURCES.txt'
installing library code to build/bdist.freebsd-11.1-RELEASE-amd64/egg
running install_lib
running build_py
creating build/bdist.freebsd-11.1-RELEASE-amd64/egg
creating build/bdist.freebsd-11.1-RELEASE-amd64/egg/pyexifinfo
copying build/lib/pyexifinfo/pyexifinfo.py -> build/bdist.freebsd-11.1-RELEASE-amd64/egg/pyexifinfo
copying build/lib/pyexifinfo/__init__.py -> build/bdist.freebsd-11.1-RELEASE-amd64/egg/pyexifinfo
byte-compiling build/bdist.freebsd-11.1-RELEASE-amd64/egg/pyexifinfo/pyexifinfo.py to pyexifinfo.pyc
byte-compiling build/bdist.freebsd-11.1-RELEASE-amd64/egg/pyexifinfo/__init__.py to __init__.pyc
creating build/bdist.freebsd-11.1-RELEASE-amd64/egg/EGG-INFO
copying pyexifinfo.egg-info/PKG-INFO -> build/bdist.freebsd-11.1-RELEASE-amd64/egg/EGG-INFO
copying pyexifinfo.egg-info/SOURCES.txt -> build/bdist.freebsd-11.1-RELEASE-amd64/egg/EGG-INFO
copying pyexifinfo.egg-info/dependency_links.txt -> build/bdist.freebsd-11.1-RELEASE-amd64/egg/EGG-INFO
copying pyexifinfo.egg-info/top_level.txt -> build/bdist.freebsd-11.1-RELEASE-amd64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/pyexifinfo-0.4.0-py2.7.egg' and adding 'build/bdist.freebsd-11.1-RELEASE-amd64/egg' to it
removing 'build/bdist.freebsd-11.1-RELEASE-amd64/egg' (and everything under it)
Processing pyexifinfo-0.4.0-py2.7.egg
Copying pyexifinfo-0.4.0-py2.7.egg to /usr/local/lib/python2.7/site-packages
Adding pyexifinfo 0.4.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/site-packages/pyexifinfo-0.4.0-py2.7.egg
Processing dependencies for pyexifinfo==0.4.0
Finished processing dependencies for pyexifinfo==0.4.0
```
