### ISSUE TITLE
pyexifinfo not working in docker

### ISSUE THREAD

**Issue by 0xbadshah** [guinslym/pyexifinfo#9]
When I create a docker container and run the command `pip install exiftool`, I get the following error:

```
Collecting pyexifinfo
  Using cached pyexifinfo-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/pyexifinfo.egg-info
    writing pip-egg-info/pyexifinfo.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/pyexifinfo.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pyexifinfo.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/pyexifinfo.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/pyexifinfo.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/pyexifinfo.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-JBBdJL/pyexifinfo/setup.py", line 95, in <module>
        result = check_if_exiftool_is_already_installed()
      File "/tmp/pip-build-JBBdJL/pyexifinfo/setup.py", line 51, in check_if_exiftool_is_already_installed
        stderr = fnull
      File "/usr/lib/python2.7/subprocess.py", line 168, in call
        return Popen(*popenargs, **kwargs).wait()
      File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-JBBdJL/pyexifinfo/
```

**Steps to reproduce:**
- `docker run --rm -ti debian:stretch-slim`
- Inside the docker container, execute the following:
  - `apt-get update`
  - `apt-get install python python-pip`
  - `pip install --upgrade pip`
  - `pip install pyexifinfo`

**Comment by aancw** [comment]
Maybe need to install exiftool package first. As mentioned in this source code:

     result = 1;
    command = ["exiftool", "-ver"]

**Comment by 0xbadshah** [comment]
`apt-get install exiftool` before the installation resolved the issue.
